In [1]:
import numpy as np

In [2]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
# Create a 2x3 array with zeros
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Create an array with a range of values
range_arr = np.arange(10)
range_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Create an array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
# Perform dot product
dot_product = np.dot(arr, arr)
dot_product

55

In [7]:
# Perform matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_multiplication = np.matmul(matrix1, matrix2)
matrix_multiplication

array([[19, 22],
       [43, 50]])

In [8]:
# Sum of array elements
sum_arr = np.sum(arr)
sum_arr

15

In [9]:
# Mean of array elements
mean_arr = np.mean(arr)
mean_arr

3.0

In [10]:
# Transpose of a matrix
transpose_matrix = np.transpose(matrix1)
transpose_matrix

array([[1, 3],
       [2, 4]])

In [11]:
# Reshape an array
reshaped_arr = np.reshape(arr, (5, 1))
reshaped_arr

array([[1],
       [2],
       [3],
       [4],
       [5]])